name: Update terraform dependencies

# on:
#   schedule:
#     - cron:  '0 6 * * *'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  dependabot-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: update terraform dependencies
        uses: plus3it/dependabot-terraform-action@p3-implementation
        with:
          github_dependency_token: 4224d33b8569bec8473980bb1bdb982639426a92
